### ISSUE TITLE
source debugging of compiled wasm

### ISSUE THREAD

**Issue by ferologics** [WebAssembly/debugging#18]
is there any support for debugging source code compiled to wasm in sight? (i.e. Rust code)

**Comment by RReverser** [comment]
It's already been working for a while for C / C++: https://developer.chrome.com/blog/wasm-debugging-2020/

As for other languages, it's up to respective toolchains to correctly emit debugging information. Rust support in particular - assuming you're talking about the Web via wasm-bindgen - is tracked on their own repo at https://github.com/rustwasm/wasm-bindgen/issues/2389.

**Comment by ferologics** [comment]
@RReverser thx, the use case I have in mind is for non-web Rust, no wasm-bindgen, just FFI pointers, compiled with `cargo build --target wasm32-unknown-unknown`, interpreted by `wasm3`. I'd like to debug this wasm in runtime like regular Rust code, put a breakpoint, step through, etc., but am not sure how/if that should work in such setup.

**Comment by RReverser** [comment]
Then it's up to wasm3 to implement debugging, although knowing the author's situation _(he's a Ukrainian who lost his home to Russian bombarding)_, I don't know if he'll have time / priority to work on it soon.

Rust itself emits debug symbols correctly though, and some runtimes like wasmtime already make use of it: https://docs.wasmtime.dev/examples-debugging.html

Either way, this is not really an issue / discussion for the standards repo, since it's up to specific runtimes to implement the necessary functionality now.

**Comment by ferologics** [comment]
okay, thanks a lot for your response, unfortunately I can't use wasmtime due to JIT compilation, so wasm3 is the only option.
